import os
import io
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak

from services.analytics_service import AnalyticsService

class PdfReportService:
    @staticmethod
    def generate_report(filepath="Student_Performance_Report.pdf", institution_name="Viswajyothi College of Engineering and Technology", department_name="Computer Science & Engineering"):
        df = AnalyticsService.get_full_dataframe()
        if df.empty:
            return False, "No data available to generate report."

        try:
            doc = SimpleDocTemplate(filepath, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
            elements = []
            styles = getSampleStyleSheet()

            # Custom styles
            styles.add(ParagraphStyle(name='MainTitle', parent=styles['Title'], fontSize=20, leading=24, spaceAfter=20, alignment=TA_CENTER, textColor=colors.darkblue))
            styles.add(ParagraphStyle(name='SubTitle', parent=styles['Normal'], fontSize=12, leading=14, spaceAfter=8, alignment=TA_CENTER))
            styles.add(ParagraphStyle(name='SectionHeader', parent=styles['Heading2'], fontSize=14, leading=16, spaceBefore=20, spaceAfter=10, textColor=colors.HexColor('#1a237e')))
            styles.add(ParagraphStyle(name='CustomBodyText', parent=styles['Normal'], fontSize=10, leading=14, spaceAfter=10))
            styles.add(ParagraphStyle(name='HighlightText', parent=styles['Normal'], fontSize=10, leading=14, spaceAfter=10, textColor=colors.red))
            styles.add(ParagraphStyle(name='InsightText', parent=styles['Normal'], fontSize=10, leading=14, spaceAfter=10, backColor=colors.HexColor('#f5f5f5'), borderPadding=10))

            # Header
            elements.append(Paragraph(f"<b>{institution_name}</b>", styles['MainTitle']))
            elements.append(Paragraph(f"Department of {department_name}", styles['SubTitle']))
            elements.append(Paragraph("<b>Academic Performance Intelligence Report</b>", styles['SubTitle']))
            
            # Determine semester
            semesters = df['semester'].unique()
            sem_str = f"Semester(s): {', '.join(map(str, sorted(semesters)))}" if len(semesters) > 0 else "N/A"
            elements.append(Paragraph(sem_str, styles['SubTitle']))
            elements.append(Paragraph(f"Date Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['SubTitle']))
            elements.append(Paragraph("Generated By: Academic Performance Intelligence System", styles['SubTitle']))
            elements.append(Spacer(1, 20))

            # Core calcs
            total_students = df['student_id'].nunique()
            student_fails = df[df['marks'] < 40].groupby('student_id')['subject_name'].count()
            students_with_fails = len(student_fails[student_fails > 0])
            students_passed = total_students - students_with_fails
            overall_pass_pct = (students_passed / total_students) * 100 if total_students > 0 else 0

            # SGPA
            sgpa_data = df.groupby('student_name')['sgpa'].first().dropna()
            avg_sgpa = sgpa_data.mean() if not sgpa_data.empty else 0
            max_sgpa = sgpa_data.max() if not sgpa_data.empty else 0
            min_sgpa = sgpa_data.min() if not sgpa_data.empty else 0
            median_sgpa = sgpa_data.median() if not sgpa_data.empty else 0
            high_performers = len(sgpa_data[sgpa_data >= 9.0]) if not sgpa_data.empty else 0

            risks = AnalyticsService.identify_at_risk_students()
            high_risk_count = len([r for r in risks if r['risk'] == 'High Risk'])

            # ---------------------------------------------------------
            # SECTION 1 - EXECUTIVE SUMMARY
            # ---------------------------------------------------------
            elements.append(Paragraph("<b>1. Executive Summary</b>", styles['SectionHeader']))
            summary_text = (
                f"This report presents an analytical overview of the academic performance for {total_students} students. "
                f"The overall pass rate stands at {overall_pass_pct:.1f}%, with a class average SGPA of {avg_sgpa:.2f}. "
                f"There are {high_performers} superior performers achieving an SGPA of 9.0 or above. Conversely, "
                f"the system has identified {high_risk_count} students as 'High Risk', requiring immediate academic engagement. "
                f"Overall, the performance trend indicates " + ("a healthy academic environment" if avg_sgpa >= 7.0 else "an area requiring systemic remediation") + " relative to institutional benchmarks."
            )
            elements.append(Paragraph(summary_text, styles['CustomBodyText']))
            elements.append(Spacer(1, 10))

            # ---------------------------------------------------------
            # SECTION 2 - CLASS OVERVIEW STATISTICS
            # ---------------------------------------------------------
            elements.append(Paragraph("<b>2. Class Overview Statistics</b>", styles['SectionHeader']))
            stats_data = [
                ['Metric', 'Value'],
                ['Total Students', str(total_students)],
                ['Total Passed', str(students_passed)],
                ['Total Failed (1+ Arrears)', str(students_with_fails)],
                ['Overall Pass Percentage', f"{overall_pass_pct:.2f}%"],
                ['Class Average SGPA', f"{avg_sgpa:.2f}"],
                ['Highest SGPA', f"{max_sgpa:.2f}"],
                ['Lowest SGPA', f"{min_sgpa:.2f}"],
                ['Median SGPA', f"{median_sgpa:.2f}"],
            ]
            t = Table(stats_data, colWidths=[200, 100])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a237e')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f5f5f5')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
            ]))
            elements.append(t)
            elements.append(Spacer(1, 20))

            # ---------------------------------------------------------
            # SECTION 3 - SGPA DISTRIBUTION ANALYSIS
            # ---------------------------------------------------------
            elements.append(Paragraph("<b>3. SGPA Distribution Analysis</b>", styles['SectionHeader']))
            if not sgpa_data.empty:
                dist_9_10 = len(sgpa_data[(sgpa_data >= 9.0)])
                dist_8_9 = len(sgpa_data[(sgpa_data >= 8.0) & (sgpa_data < 9.0)])
                dist_7_8 = len(sgpa_data[(sgpa_data >= 7.0) & (sgpa_data < 8.0)])
                dist_6_7 = len(sgpa_data[(sgpa_data >= 6.0) & (sgpa_data < 7.0)])
                dist_fail = len(sgpa_data[(sgpa_data < 6.0)])

                dist_table = [
                    ['SGPA Range', 'Number of Students', 'Percentage'],
                    ['9.0 – 10.0', str(dist_9_10), f"{(dist_9_10/total_students)*100:.1f}%"],
                    ['8.0 – 8.99', str(dist_8_9), f"{(dist_8_9/total_students)*100:.1f}%"],
                    ['7.0 – 7.99', str(dist_7_8), f"{(dist_7_8/total_students)*100:.1f}%"],
                    ['6.0 – 6.99', str(dist_6_7), f"{(dist_6_7/total_students)*100:.1f}%"],
                    ['< 6.0', str(dist_fail), f"{(dist_fail/total_students)*100:.1f}%"],
                ]
                t_dist = Table(dist_table, colWidths=[150, 150, 100])
                t_dist.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#283593')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                    ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
                ]))
                elements.append(t_dist)
                elements.append(Spacer(1, 15))

                # Chart
                fig, ax = plt.subplots(figsize=(6, 3.5))
                ranges = ['9-10', '8-8.99', '7-7.99', '6-6.99', '<6.0']
                counts = [dist_9_10, dist_8_9, dist_7_8, dist_6_7, dist_fail]
                ax.bar(ranges, counts, color=['#4CAF50', '#8BC34A', '#FFEB3B', '#FF9800', '#F44336'])
                ax.set_title("SGPA Distribution")
                ax.set_ylabel("No. of Students")
                
                img_data = io.BytesIO()
                plt.tight_layout()
                plt.savefig(img_data, format='png', dpi=150)
                plt.close(fig)
                img_data.seek(0)
                elements.append(Image(img_data, width=400, height=230))
                
                dist_interp = f"The distribution is characterized by the highest concentration in the {ranges[counts.index(max(counts))]} tier. "
                elements.append(Paragraph(f"<b>Interpretation:</b> {dist_interp}", styles['CustomBodyText']))
                elements.append(Spacer(1, 10))
            else:
                elements.append(Paragraph("Insufficient data for SGPA analysis.", styles['CustomBodyText']))

            # ---------------------------------------------------------
            # SECTION 4 - SUBJECT-WISE ANALYSIS
            # ---------------------------------------------------------
            elements.append(PageBreak())
            elements.append(Paragraph("<b>4. Subject-wise Analysis</b>", styles['SectionHeader']))
            
            stats = AnalyticsService.calculate_subject_difficulty()
            if stats:
                subj_data = [['Subject Name', 'Course Avg', 'Pass %', 'Difficulty']]
                for subj, data in sorted(stats.items(), key=lambda x: x[1].get('difficulty_score', 0), reverse=True):
                    pass_pct = data.get('pass_percent', 0)
                    subj_data.append([
                        Paragraph(str(subj), styles['CustomBodyText']), 
                        f"{data.get('avg_marks', 0):.1f}",
                        f"{pass_pct:.1f}%",
                        data.get('classification', 'Unknown')
                    ])
                    
                t_subj = Table(subj_data, colWidths=[200, 80, 80, 100])
                t_subj.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#00695c')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                    ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
                ]))
                elements.append(t_subj)
                elements.append(Spacer(1, 15))
                
                # Chart
                if len(stats) > 0:
                    fig, ax = plt.subplots(figsize=(7, 3.5))
                    s_names = [s[:15]+"..." if len(s)>15 else s for s in stats.keys()]
                    s_avgs = [data.get('avg_marks', 0) for data in stats.values()]
                    ax.barh(s_names, s_avgs, color='#00897B')
                    ax.set_xlabel('Average Marks')
                    ax.set_title('Subject Averages Comparison')
                    img_data2 = io.BytesIO()
                    plt.tight_layout()
                    plt.savefig(img_data2, format='png', dpi=150)
                    plt.close(fig)
                    img_data2.seek(0)
                    elements.append(Image(img_data2, width=450, height=220))
            else:
                elements.append(Paragraph("No subject data available.", styles['CustomBodyText']))

            # ---------------------------------------------------------
            # SECTION 5 - TOP PERFORMERS
            # ---------------------------------------------------------
            elements.append(PageBreak())
            elements.append(Paragraph("<b>5. Top Performers (Top 10)</b>", styles['SectionHeader']))
            if not sgpa_data.empty:
                top_students = sgpa_data.sort_values(ascending=False).head(10)
                top_data = [['Rank', 'Student Name', 'SGPA', 'Status']]
                rank = 1
                for name, s_sgpa in top_students.items():
                    top_data.append([str(rank), name, f"{s_sgpa:.2f}", "Distinction" if s_sgpa >= 8.5 else "First Class"])
                    rank += 1
                    
                t_top = Table(top_data, colWidths=[50, 200, 80, 100])
                t_top.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0277bd')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                    ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#e1f5fe')), # Topper highlight
                ]))
                elements.append(t_top)
            else:
                elements.append(Paragraph("SGPA tracking unavailable for evaluating top performers.", styles['CustomBodyText']))
                
            # ---------------------------------------------------------
            # SECTION 6 - AT-RISK STUDENTS ANALYSIS
            # ---------------------------------------------------------
            elements.append(Spacer(1, 20))
            elements.append(Paragraph("<b>6. At-Risk Students Analysis</b>", styles['SectionHeader']))
            if risks:
                safe = len([r for r in risks if r['risk'] == 'Safe'])
                mod = len([r for r in risks if r['risk'] == 'Moderate Risk'])
                high = len([r for r in risks if r['risk'] == 'High Risk'])
                
                risk_summary = [['Category', 'Count', 'Percentage']]
                risk_summary.append(['Safe', str(safe), f"{(safe/len(risks)*100):.1f}%"])
                risk_summary.append(['Moderate Risk', str(mod), f"{(mod/len(risks)*100):.1f}%"])
                risk_summary.append(['High Risk', str(high), f"{(high/len(risks)*100):.1f}%"])
                
                t_risk = Table(risk_summary, colWidths=[150, 100, 100])
                t_risk.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#c62828')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ]))
                elements.append(t_risk)
                elements.append(Spacer(1, 10))
                
                high_risk_list = [r['name'] for r in risks if r['risk'] == 'High Risk'][:15]
                if high_risk_list:
                    elements.append(Paragraph("<i>High Risk Roster (Top 15):</i> " + ", ".join(high_risk_list), styles['HighlightText']))
            else:
                 elements.append(Paragraph("No risk tracking data available.", styles['CustomBodyText']))

            # ---------------------------------------------------------
            # SECTION 7 - ARREAR ANALYSIS
            # ---------------------------------------------------------
            elements.append(Paragraph("<b>7. Arrear Analysis</b>", styles['SectionHeader']))
            if not df.empty:
                fails_df = df[df['marks'] < 40]
                arrear_counts = fails_df.groupby('student_id')['subject_name'].count()
                arr_1 = len(arrear_counts[arrear_counts == 1])
                arr_2 = len(arrear_counts[arrear_counts == 2])
                arr_3 = len(arrear_counts[arrear_counts >= 3])
                
                elements.append(Paragraph(f"• Students with exactly 1 Arrear: {arr_1}", styles['CustomBodyText']))
                elements.append(Paragraph(f"• Students with exactly 2 Arrears: {arr_2}", styles['CustomBodyText']))
                elements.append(Paragraph(f"• Students with 3+ Arrears: {arr_3}", styles['CustomBodyText']))
                
                sub_fails = fails_df['subject_name'].value_counts()
                if not sub_fails.empty:
                    top_fail_sub = sub_fails.index[0]
                    elements.append(Paragraph(f"<b>Most frequently failed subject:</b> {top_fail_sub} ({sub_fails.iloc[0]} failures)", styles['HighlightText']))
            
            # ---------------------------------------------------------
            # SECTION 8 - FACULTY PERFORMANCE ANALYSIS
            # ---------------------------------------------------------
            elements.append(PageBreak())
            elements.append(Paragraph("<b>8. Faculty Performance Analysis</b>", styles['SectionHeader']))
            fac_perf = AnalyticsService.evaluate_faculty_performance()
            if fac_perf:
                fac_data = [['Faculty Name', 'Subjects Handled', 'Subject Avg', 'Pass %']]
                for fac, perf in sorted(fac_perf.items(), key=lambda x: x[1]['pass_percent'], reverse=True):
                     fac_data.append([
                         fac, 
                         Paragraph(", ".join(perf['subjects']), styles['CustomBodyText']), 
                         f"{perf['average']:.1f}", 
                         f"{perf['pass_percent']:.1f}%"
                     ])
                t_fac = Table(fac_data, colWidths=[120, 150, 80, 80])
                t_fac.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4527a0')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ]))
                elements.append(t_fac)
            else:
                elements.append(Paragraph("No faculty assignment data exists.", styles['CustomBodyText']))

            # ---------------------------------------------------------
            # SECTION 9 - COMPARATIVE ANALYSIS
            # ---------------------------------------------------------
            elements.append(Paragraph("<b>9. Comparative Analysis</b>", styles['SectionHeader']))
            elements.append(Paragraph("Comparative data across semesters is limited in the current dataset slice. "
                                      "Longitudinal tracking requires multi-semester ingestion.", styles['CustomBodyText']))

            # ---------------------------------------------------------
            # SECTION 10 - INTELLIGENT INSIGHTS
            # ---------------------------------------------------------
            elements.append(Paragraph("<b>10. Intelligent Insights</b>", styles['SectionHeader']))
            from services.insights_service import InsightsService
            auto_insights = InsightsService.generate_ai_insights()
            for insight in auto_insights:
                elements.append(Paragraph(f"💡 {insight}", styles['InsightText']))
            
            # Dynamic additions
            if stats:
                 diff_sub = max(stats.keys(), key=lambda k: stats[k].get('difficulty_score', 0))
                 elements.append(Paragraph(f"💡 System flags '{diff_sub}' as structurally difficult. Immediate curricular review recommended.", styles['InsightText']))

            # ---------------------------------------------------------
            # SECTION 11 - RECOMMENDATIONS
            # ---------------------------------------------------------
            elements.append(PageBreak())
            elements.append(Paragraph("<b>11. Recommendations</b>", styles['SectionHeader']))
            recs = (
                "<b>1. Corrective Pedagogy:</b> Conduct remedial sessions tailored for the most fundamentally challenging subjects.<br/><br/>"
                "<b>2. Intervention Strategy:</b> Institute mandatory mentoring and academic monitoring for the High Risk cross-section.<br/><br/>"
                "<b>3. Excellence Amplification:</b> Provide advanced tier assignments or projects to top decile students to ensure continued intellectual engagement.<br/><br/>"
                "<b>4. Faculty Workshopping:</b> Peer-review teaching techniques between highest and lowest-performing metric clusters."
            )
            elements.append(Paragraph(recs, styles['CustomBodyText']))

            # ---------------------------------------------------------
            # SECTION 12 - APPENDIX
            # ---------------------------------------------------------
            elements.append(Paragraph("<b>12. Appendix</b>", styles['SectionHeader']))
            elements.append(Paragraph("<b>A. Grading Schema</b>", styles['CustomBodyText']))
            grade_schema = [
                ['Grade', 'Point', 'Status'],
                ['O / S', '10', 'Outstanding'],
                ['A+', '9', 'Excellent'],
                ['A', '8', 'Very Good'],
                ['B+', '7', 'Good'],
                ['B', '6', 'Above Average'],
                ['C', '5', 'Average'],
                ['P', '4', 'Pass'],
                ['F / FE / I', '0', 'Fail / Incomplete']
            ]
            t_grade = Table(grade_schema, colWidths=[100, 100, 150])
            t_grade.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#424242')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ]))
            elements.append(t_grade)
            elements.append(Spacer(1, 15))
            
            elements.append(Paragraph("<b>B. Statistical Methodologies</b>", styles['CustomBodyText']))
            methodology = (
                "<i>Difficulty Score Calculation:</i> Weighted aggregate factoring pass rate (60% weight) and absolute average attainment (40%).<br/>"
                "<i>Risk Engine:</i> Considers trailing SGPA differentials and cumulative failed thresholds aligned with academic warnings."
            )
            elements.append(Paragraph(methodology, styles['CustomBodyText']))

            # Build document
            doc.build(elements)
            return True, f"Institution-Grade Report successfully exported to {filepath}"

        except Exception as e:
            return False, f"Failed to generate report PDF: {str(e)}"
